config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :users, except: [:destroy]
  resources :questions, except: [:destroy] do
    resources :answers, except: [:show]
  end
  resources :answers do
    resources :comments, only: [:new, :create]
  end

  post '/questions/vote' => 'questions#vote'
  post '/answers/vote' => 'answers#vote'
  resources :votes, only: [:new, :create], path: '/:obj_type/:obj_id/votes'
  resources :tags, only: [:index, :show]

  get 'register' => 'users#new', as: 'register'
  post 'register' => 'users#create'
  get 'profile' => 'sessions#show'
  get 'login' => 'sessions#login_form'
  post 'login' => 'sessions#login'
  get 'logout' => 'sessions#logout', as: 'logout'
  get '/auth/:provider/callback' => 'sessions#create'

  get '/recent' => 'questions#recent'
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags
  has_many :votes, as: :voteable, dependent: :destroy

  validates_presence_of :title, :body
  validates_presence_of :user, message: "You must be logged in to create questions."

  def total_points#really slow have the bd do this later
    self.votes.sum(:value)
  end

  def self.by_recency
    order(updated_at: :desc)
  end

  def last_respondent
    self.answers.last.user.username
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def index
    # binding.pry #used to stop flow and call the ddog helpers to create metrics
    @questions = Question.by_recency
  end

  def edit
  end

  def new
    @question = Question.new
    @tag = Tag.new
  end

  def create
    new_q = Question.new(valid_params)
    if session[:user_id]
      current_user.questions << new_q
      new_q.tags << make_tags
      redirect_to root_path
    else
      flash[:errors] = "You must be logged in to create questions."
      redirect_to new_question_path
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

  def update
  end

  def vote
    parent_question = Question.find_by(id: params[:question_id])
    make_vote(parent_question)
  end

  def recent
    @questions = Question.by_recency.limit(10)
  end

  def valid_params
    params.require(:question).permit(:title,:body)
  end

  def tag_params
    params.require(:tag).permit(:description)
  end

  def make_tags
    tag_params[:description].split.map { |desc| Tag.where(description: desc).first_or_create }
  end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/questions/_new_form.html.erb
<%= flash[:errors] %>
<%= form_for @question do |f|%>
<div class="form">
<label for="field1"><span>Title <span class="required">*</span></span><%= f.text_field :title, placeholder: 'Title', :size=>"40" %></label>
<label for="field2"><span>Content <span class="required">*</span></span><%= f.text_area :body, placeholder: 'Body', :rows => "10", :cols => "40" %></label>
<label for= "field3"><span>Tags</span><%= fields_for @tag do |ff| %>
      <%= ff.text_field :description, placeholder: 'Tags', :size=>"40" %>
     <% end %></label>
<label><span>&nbsp;</span> <%= f.submit "Shaq away!" %></label>
<% end %>
</div>

app/views/questions/_question.html.erb
<ul class = "content" >

<% @questions.each do |q| %>
  <li class = "question-header"><%= q.total_points %> | <%= link_to q.title, question_path(q) %></li>
  <ul>
    <li class = "question-content"><%= q.body %></li>
    <li class="username">asked by <%= link_to q.user.username, user_path(q.user.id) %></li>
  </ul>
<% end %>

</ul>

app/views/questions/index.html.erb
<div class="header-unit">

<div id="video-container">
  <div id = "banner">
  <img src="/imgs/shaq.png" alt="shaq-banner" />
  </div>

<video id ="vid-div" autoplay loop class="fillWidth">
<source data-src="imgs/shaq.mp4" type="video/mp4"/>
<source data-src="imgs/shaq.webm" type="video/webm"/>
<source data-src="imgs/shaq.ogv" type="video/ogv"/>
Your browser does not support the video tag. I suggest you upgrade your browser.
</video>
</div><!-- end video-container -->
</div><!-- end .header-unit -->




<%= render 'question' %>

app/views/questions/recent.html.erb
<ul class = "content">
  <h2> Recently Active Questions </h2>
  <% @questions.each do |question|%>
    <li class = "question-header"><%= link_to question.title, question_path(question) %></li>
    <ul>
    <li class="username">asked by: <%= link_to question.user.username, user_path(question.user) %></li>
    </ul>
  <% end %>
</ul>

app/views/questions/show.html.erb
<div class = "content" >

<h1><%= @question.title%></h1><br>

<h2><%= @question.body %></h2>

<h3 class="username">asked by <%= link_to @question.user.username, user_path(@question.user) %></h3>

<h3><%= @question.answers.count %> Answers</h3>
  <h4>Tags:</h4><% @question.tags.each do |tag|%>
 <span class="tag-intro"><%= link_to tag.description, tag_path(tag) %></span>
<% end %>

  <div class ='master-container'>
    <h3>
      score: <span class= 'point-value'><%= @question.total_points %></span>
      <div class = "vote-button"> <%= button_to "⤴", questions_vote_path, params: {question_id: @question.id, vote_direction: 1}%></div>
      <div class  = "vote-button"> <%= button_to "⤵", questions_vote_path, params: {question_id: @question.id, vote_direction: -1}%></div>
    </h3>
  <ul class = "answer-list">
  <% @answers.each do |answer| %>
    <%= render partial: 'answers/single_answer', locals: {answer: answer}, layout: false %>
  <% end %>
  </ul>

</div>

<div id = 'link-container'>
<%= link_to "Have an Answer?", new_question_answer_path(@question), class: 'make-answer-key' %>
</div>

<div id = 'answer-form-container'></div>