config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :users, except: [:destroy]
  resources :questions, except: [:destroy] do
    resources :answers, except: [:show]
  end
  resources :answers do
    resources :comments, only: [:new, :create]
  end

  post '/questions/vote' => 'questions#vote'
  post '/answers/vote' => 'answers#vote'
  resources :votes, only: [:new, :create], path: '/:obj_type/:obj_id/votes'
  resources :tags, only: [:index, :show]

  get 'register' => 'users#new', as: 'register'
  post 'register' => 'users#create'
  get 'profile' => 'sessions#show'
  get 'login' => 'sessions#login_form'
  post 'login' => 'sessions#login'
  get 'logout' => 'sessions#logout', as: 'logout'
  get '/auth/:provider/callback' => 'sessions#create'

  get '/recent' => 'questions#recent'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question, touch: true
  has_many :comments
  has_many :votes, as: :voteable, dependent: :destroy

  validates_presence_of :body, :question_id ,:user_id

  def total_points#really slow have the bd do this later
    self.votes.sum(:value)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    if request.xhr?
      render 'answers/new', layout: false
    else
      render 'answers/new'
    end
  end

  def create
    question = Question.find(params[:question_id])
    new_a = Answer.new(valid_params)
    if request.xhr?
      answer_creation_Async(question, new_a)
    else
      answer_creation_sync(question, new_a)
    end
  end

  def vote
    parent_answer = Answer.find_by(id: params[:answer_id])
    make_vote(parent_answer)
  end

  def answer_creation_Async(question, new_a)
    if current_user
      if new_a.valid?
        question.answers << new_a
        render partial: 'answers/single_answer', layout: false, locals:{answer: new_a}
      else
        render :nothing => true, :status => 500
      end
    else
      render :nothing => true, :status => 403
    end
  end

  def answer_creation_sync(question, new_a)
    if current_user
      if new_a.valid?
        question.answers << new_a
        redirect_to question
      else
        flash[:errors] = new_a.errors.messages.values.join("\n")
        redirect_to new_question_answer_path
      end
    else
      flash[:errors] = "You must be logged in to add answers."
      redirect_to new_question_answer_path
    end
  end


  def valid_params
    params.require(:answer).permit(:body, :user_id, :question_id)
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/views/answers/_new_form.html.erb
<%= form_for @answer, url: question_answers_path(@question) do |f|%>
<div class="form">
<label for="field1"><span>Answer <span class="required">*</span></span><%= f.text_area :body, placeholder: 'Body', :rows => "10", :cols => "40" %></label>
  <%= f.hidden_field :user_id, value: session[:user_id]%>
  <%= f.hidden_field :question_id, value: @question.id %>
<label><%= f.submit "Answer!" %></label>
<% end %>
</div>

app/views/answers/_single_answer.html.erb
<div class = 'specific-answer'>
  <span class = "point-value"><%= answer.total_points %> | </span>
  <div class = "vote-button"> <%= button_to "⤴", answers_vote_path, params: {answer_id: answer.id, vote_direction: 1}%></div>
  <div class = "vote-button"> <%= button_to "⤵", answers_vote_path, params: {answer_id: answer.id, vote_direction: -1}%></div>
  <div><%= answer.body %></div>
  <h5>answered by <%= link_to answer.user.username, user_path(answer.user) %></h5>
  <div><%= answer.created_at %></div>

  <ul class = "comment-list">
  <% answer.comments.each do |comment| %>
    <%= render partial: 'comments/comment', locals: {comment: comment}, layout: false %>
  <% end %>
  </ul>
  <div id = 'link-comment-container'>
  <%= link_to "Comment on this Answer", new_answer_comment_path(answer), class: 'make-comment-key' %>
  </div>
  <div id = 'comment-form-container'></div>

</div>

app/views/answers/new.html.erb
<%= render 'new_form', layout: false %>

app/views/answers/show.html.erb
<div>Question ID: <%= @question.id %></div>
<div>Question Title: <%= @question.title %></div>
<div>Answer Body: <%= @answer.body %></div>
<div>Answer ID: <%= @answer.id %></div>