config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :users, except: [:destroy]
  resources :questions, except: [:destroy] do
    resources :answers, except: [:show]
  end
  resources :answers do
    resources :comments, only: [:new, :create]
  end

  post '/questions/vote' => 'questions#vote'
  post '/answers/vote' => 'answers#vote'
  resources :votes, only: [:new, :create], path: '/:obj_type/:obj_id/votes'
  resources :tags, only: [:index, :show]

  get 'register' => 'users#new', as: 'register'
  post 'register' => 'users#create'
  get 'profile' => 'sessions#show'
  get 'login' => 'sessions#login_form'
  post 'login' => 'sessions#login'
  get 'logout' => 'sessions#logout', as: 'logout'
  get '/auth/:provider/callback' => 'sessions#create'

  get '/recent' => 'questions#recent'
end

app/views/layouts/_header.html.erb
<div class = "nav">
  <ul>
    <li id = "search-bar">
    <%= form_tag tags_path, method: :get do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Tags" %>
    <% end %> </li>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Tags', tags_path %></li>
    <li><%= link_to 'Recent', recent_path %></li>
  <% if session[:user_id] %>
    <li><%= link_to 'Profile', profile_path(current_user) %></li>
    <li><%= link_to 'Shaq a Question!', new_question_path %></li>
    <li><%= link_to 'Log out', logout_path %></li>
  <% else %>
    <li><%= link_to 'Register', register_path %></li>
    <li><%= link_to 'Log in', login_path %></li>
  <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>shaqOverflow</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700|Merriweather+Sans' rel='stylesheet' type='text/css'>
</head>
<header></header>

<body>
  <%= render 'layouts/header' %>

</body>

<body>

<%= yield %>

</body>

<footer>
  <img src="/imgs/shaq_footer.png" alt="shaq-banner" />
</footer>

</html>